title: digits
description: An adaptation of the template for quickly starting Next.js application development
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
